apiVersion: v1
kind: Secret
metadata:
  name: amit-docker-registry-secret
  annotations:
    replicator.v1.mittwald.de/replicate-from: cluster-secrets/docker-registry-mlf-configjson
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  .dockerconfigjson: e30K
type: kubernetes.io/dockerconfigjson